# Generated by Django 3.0.7 on 2020-06-11 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cls_name', models.CharField(max_length=10, verbose_name='班级')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_name', models.CharField(max_length=30, verbose_name='名字')),
                ('stu_sex', models.IntegerField(default=0, verbose_name='性别0是女')),
                ('stu_cls', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student.Class')),
            ],
        ),
    ]
